---
# install the AIDE IDS on a server

  - name: Install all those dependencies
    apt: pkg={{item}} state=present
    with_items:
      - aide
      - aide-common
    tags:
      - install

  - name: change up the email to send to us
    lineinfile:
      dest: /etc/default/aide
      regexp: '^MAILTO'
      line: "MAILTO="
      state: present
    tags:
      - install

  - name: no need for an email if nothing has changed
    lineinfile:
      dest: /etc/default/aide
      regexp: '^QUIETREPORTS'
      line: "QUIETREPORTS=yes"
      state: present
    tags:
      - install

  - name: Just do the sha256 checksum or it takes forever
    lineinfile: 
      dest=/etc/aide/aide.conf 
      regexp="^Checksums" 
      line="Checksums = sha256" 
      state=present
    tags:
      - install

  - name: change up aide.conf to standards
    lineinfile:
      dest: /etc/aide/aide.conf
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      state: present
    with_items:
        -
          regex: "^#!/home"
          line: "#!/home/.*	 	# do we care about home? not sure yet"
        -
          regex: "^#!/root/.drush"
          line: "#!/root/.drush/.*	 	# roots drush cache is ok"
        -
          regex: "^!/tmp/tomcat7-tomcat7-tmp"
          line: "!/tmp/tomcat7-tomcat7-tmp/.*	 # Tomcat temp dir"
        -
          regex: "^!/var/log/.*"
          line: "!/var/log/.*     	# ignore the log dir it changes too often"
        -
          regex: "^!/var/spool/.*"
          line: "!/var/spool/.*   	# ignore spool dirs as they change too often"
        -
          regex: "^!/var/adm/utmp"
          line: "!/var/adm/utmp$  	# ignore the file /var/adm/utmp"
        -
          regex: "^!/lib/"
          line: "!/lib/.*          	# lib is too busy"
        -
          regex: "^!/dev/"
          line: "!/dev/.*	 	# dev is too busy"
        -
          regex: "^!/opt/"
          line: "!/opt/.*		# nothing in there"
        -
          regex: "^!/proc/"
          line: "!/proc/.* 		# really noisy"
        -
          regex: "^!/srv"
          line: "!/srv/.*		# nothing in there really"
        -
          regex: "^!/run/"
          line: "!/run/.*		# pid files and such change often"
        -
          regex: "^!/sys/"
          line: "!/sys/.*		# OS level stuff"
        -
          regex: "^!/var/cache"
          line: "!/var/cache/.*	 	# constant changes"
        -
          regex: "^!/var/lib"
          line: "!/var/lib/.*		# constant changes"
        -
          regex: "^!/root/.cache/"
          line: "!/root/.cache/.* 	# mostly the duplicity stuff"
        -
          regex: "^!/tmp/.ansible"
          line: "!/tmp/.ansible*	# changes too much"
        -
          regex: "^!/root/.*/backups"
          line: "!/root/.*/backups.*	 # AS files"
        -
          regex: "^!/root/.*/data"
          line: "!/root/.*/data.*	 # AS Files"
        -
          regex: "^!/tmp/hsperfdata_solr/"
          line: "!/tmp/hsperfdata_solr/.* # SOLR stuff"
        -
          regex: "!/tmp/hsperfdata_tomcat7/"
          line: "!/tmp/hsperfdata_tomcat7/.* # SOLR stuff"
        -
          regex: "^!/root/.bash_history"
          line: "!/root/.bash_history	 # Don't really need to know"
        -
          regex: "^!/root/.viminfo"
          line: "!/root/.viminfo	 # Don't really need to know"
        -
          regex: "^!/home/.*/.ansible"
          line: "!/home/.*/.ansible.*	 # Ansible temp stuff changes every run"
        -
          regex: "^!/.swatch_script"
          line: "!/.swatch_script.*	 # Swatch temp files"
    tags:
      - install

  - name:  Add crontab to reset DB nightly
    cron:
      user="root"
      name="Redo Aide DB nightly"
      hour=23
      minute=45
      job="/usr/sbin/aideinit -y -f"
    tags:
      - install

    notify:
      - init aide database
